---


- name: Install yum repo
  yum_repository:
    name: code
    description: vscode
    file: vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    baseurl: https://packages.microsoft.com/yumrepos/vscode

- name: Install vscode
  yum:
    name: code
    state: present
    update_cache: true

- name: Install extensions
  command: "code --install-extension {{ item }}"
  become: true
  become_user: "{{ vscode_user|default('vagrant') }}"
  register: result
  loop: "{{ vscode_extensions }}"
  changed_when: result.stdout is not search('is already installed.')
