#!/usr/bin/env ansible-playbook --ask-vault-pass
---

- name: Chapter 8 examples
  hosts: localhost
  connection: local

  tasks:
    - name: Test of filter plugin
      template:
        src: example-8-10.j2
        dest: ./example.txt
        mode: 0644

- name: Chapter 8 examples
  hosts: dev,prod

  tasks:
    - name: Add my public key for SSH
      authorized_key:
        user: vagrant
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
        key_options: 'from="10.0.2.2"'
        exclusive: true

    - name: Copy authorized_keys template
      template:
        src: authorized_keys.j2
        dest: /home/vagrant/.ssh/authorized_keys
        owner: vagrant
        group: vagrant
        mode: 0600

    - name: Add default public key for vagrant user
      authorized_key:
        user: vagrant
        key: "{{ lookup('pipe', pubkey_cmd ) }}"
      vars:
        pubkey_cmd: 'ssh-keygen -y -f ~/.vagrant.d/insecure_private_key'

    - name: Get the current shell
      debug: msg="{{ lookup('env', 'SHELL') }}"

    - name: Create deploy user, save random password in pw.txt
      become: true
      user:
        name: deploy
        password: "{{ lookup('password', 'pw.txt encrypt=sha512_crypt') }}"

    - name: Output message from template
      debug:
        msg: "{{ lookup('template', 'message.j2') }}"

- name: More examples from chapter 8
  hosts: localhost
  connection: local

  tasks:
    - name: "Show Sue's email"
      debug:
        msg: "{{ lookup('csvfile', 'sue file=users.csv delimiter=, col=1') }}"

    - name: Look up TXT record
      debug:
        msg: "{{ lookup('dig', 'ansiblebook.com', 'qtype=TXT') }}"

    - name: Look up values in Redis
      environment:
        ANSIBLE_REDIS_HOST: localhost
        ANSIBLE_REDIS_PORT: 6379
      debug:
        msg: "{{ lookup('redis', 'weather','temp' ) }}"

    - name: Iterate with loop
      debug:
        msg: "KPI: {{ item.kpi }} prio: {{ i + 1 }} goto: {{ item.dept }}"
      loop:
        - kpi: availability
          dept: operations
        - kpi: performance
          dept: development
        - kpi: security
          dept: security
      loop_control:
        index_var: i
        pause: 3

    - name: Iterate over lines in a file
      say:
        msg: "{{ item }}."
      with_lines:
        - cat files/turing.txt

- name: Chapter 8 examples
  hosts: dev,prod
  vars:
    list_of_packages:
      - git
      - python3

  tasks:

    - name: Install packages
      become: true
      package:
        name: "{{ list_of_packages }}"
        state: present

    - name: Add public keys to account
      become: true
      authorized_key:
        user: deploy
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - /var/keys/*.pub
        - keys/*.pub

    - name: Iterate over ansible_enp0s8
      debug:
        msg: "{{ item.key }}={{ item.value }}"
      with_dict: "{{ ansible_enp0s8.ipv4 }}"

    - name: Add authorized_key for SSH
      authorized_key:
        user: vagrant
        key: "{{ item }}"
        key_options: 'from="10.0.2.2"'
        exclusive: true
      with_file: "{{ '~/.ssh/id_ed25519.pub' }}"

    - name: Add users
      become: true
      user:
        name: "{{ user.name }}"
      with_items:
        - {name: gil}
        - {name: sarina}
        - {name: leanne}
      loop_control:
        loop_var: user

    - name: Mkdir
      become: true
      file:
        path: /etc/nginx/conf.d/
        state: directory
        mode: '0750'

    - name: Create nginx vhost configs
      become: true
      template:
        src: "{{ item.domain }}.conf.j2"
        dest: "/etc/nginx/conf.d/{{ item.domain }}.conf"
        mode: '0640'
      with_items:
        - {domain: www1.example.com, tls_enabled: true}
        - {domain: www2.example.com, tls_enabled: false}
        - {domain: www3.example.com, tls_enabled: false,
           aliases: [edge2.www.example.com, eu.www.example.com]}

    - block:
        - debug: msg="You will see a failed tasks right after this"

        - name: Returns 1
          command: /usr/bin/false
          changed_when: false

        - debug: msg="You never see this message"
      rescue:
        - debug: msg="You see this message in case of failure in the block"
      always:
        - debug: msg="This will be always executed"

    - name: Test of ansible vault
      debug: var=secret_key
...
