---

- name: Generate the settings file
  template:
    src: local_settings.py.j2
    dest: "{{ mezzanine_settings_path }}/local_settings.py"
    mode: 0750

- name: Apply migrations to database, collect static content
  django_manage:
    command: "{{ item }}"
    app_path: "{{ mezzanine_proj_path }}"
    virtualenv: "{{ mezzanine_venv_path }}"
  with_items:
    - migrate
    - collectstatic

- name: Set the site id
  script: setsite.py
  environment:
    PATH: "{{ mezzanine_venv_path }}/bin"
    PROJECT_DIR: "{{ mezzanine_proj_path }}"
    PROJECT_APP: "{{ mezzanine_proj_app }}"
    DJANGO_SETTINGS_MODULE: "{{ mezzanine_proj_app }}.settings"
    WEBSITE_DOMAIN: "{{ live_hostname }}"

- name: Set the admin password
  script: setadmin.py
  environment:
    PATH: "{{ mezzanine_venv_path }}/bin"
    PROJECT_DIR: "{{ mezzanine_proj_path }}"
    PROJECT_APP: "{{ mezzanine_proj_app }}"
    ADMIN_PASSWORD: "{{ admin_pass }}"

- name: Set the gunicorn config file
  template:
    src: gunicorn.conf.py.j2
    dest: "{{ mezzanine_proj_path }}/gunicorn.conf.py"
    mode: 0750

- name: Set the supervisor config file
  become: true
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/mezzanine.conf
    mode: 0640
  notify: restart supervisor

- name: Install poll twitter cron job
  cron:
    name: "poll twitter"
    minute: "*/5"
    user: "{{ mezzanine_user }}"
    job: "{{ mezzanine_manage }} poll_twitter"
...
