#!/usr/bin/env ansible-playbook
---

- hosts: all:!localhost
  gather_facts: true

  vars:
    # Install Software Collections?
    collections_enabled: true
    # Devtoolset to compile with
    DTSVER: 8
    # C++ compiler to compile
    GCCVER: '11.2.0'
    dependencies_url_signed: false
    # Boost version to compile
    boost_version: 1.66.0
    boost_cflags: '-fPIC -fno-rtti'
    boost_cxxflags: '-fPIC -fno-rtti'
    boost_properties: "link=static threading=multi runtime-link=shared"

  roles:
    - role: base_python
    - role: base_cmake
    - role: base_gcc
    - role: compile_gcc
    - role: base_boost
...
