#!/usr/bin/env ansible-playbook
---

- name: Provision Docker VMs
  hosts: dockerhosts
  become: true
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        update_cache: true
        cache_valid_time: 3600
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg-agent
        - python3-pip
        - software-properties-common

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: false
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Install Docker python client
      pip:
        name: docker
        state: present

    - name: Download docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.1.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: Grant docker to vagrant user
      user:
        name: vagrant
        groups: docker

- name: Provision database machine
  hosts: mysql
  become: true
  gather_facts: false

  tasks:
    - name: Install packages for mysql
      apt:
        update_cache: true
        cache_valid_time: 3600
        name:
          - mysql-server
          - python3-pip
        state: present

    - name: Install requirements
      pip:
        name: PyMySQL
        state: present
        executable: /usr/bin/pip3

- name: Provision RHEL8 VM
  hosts: rhel8
  become: true
  gather_facts: true

  tasks:
    - name: Update packages
      yum:
        name: "*"
        state: latest
      tags:
        - update
...
