---

- src: dockpack.base_crontab
  name: crontab

- src: dockpack.base_common
  name: common

- src: dockpack.base_epel
  name: epel

- src: dockpack.base_nettime
  name: nettime

- src: dockpack.base_rsyslog
  name: rsyslog

...
